### ISSUE TITLE
Comparing R-Transformer with Relational RNN

### ISSUE THREAD

**Issue by flrngel** [DSE-MSU/R-transformer#1]
Hi!
Currently I'm reading your paper.
In my opinion, your result can be compare with Relational RNN(https://arxiv.org/abs/1806.01822).
Relational RNN has RMC(Relational Memory Core) concept, which uses multi-head dot product attention as core.
Can you compare the peformance with Relational RNN?

Thanks!

**Comment by alphadl** [comment]
This is the link to Reddit's discussion of this paper~ https://www.reddit.com/r/textdatamining/comments/cdgp8x/rtransformer_recurrent_neural_network_enhanced/
